# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/SDUP_2020_projekt_H/Huffman/Huffman.cache/wt [current_project]
set_property parent.project_path D:/SDUP_2020_projekt_H/Huffman/Huffman.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/SDUP_2020_projekt_H/ip_repo/huffman_ip_1.0 [current_project]
set_property ip_output_repo d:/SDUP_2020_projekt_H/Huffman/Huffman.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/SDUP_2020_projekt_H/Huffman/Huffman.srcs/sources_1/new/raw_decoder.v
  D:/SDUP_2020_projekt_H/Huffman/Huffman.srcs/sources_1/new/create_tree.v
  D:/SDUP_2020_projekt_H/Huffman/Huffman.srcs/sources_1/new/huffman_decoder.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/SDUP_2020_projekt_H/Huffman/Huffman.srcs/constrs_2/new/huffman_decoder.xdc
set_property used_in_implementation false [get_files D:/SDUP_2020_projekt_H/Huffman/Huffman.srcs/constrs_2/new/huffman_decoder.xdc]


synth_design -top huffman_decoder -part xc7z020clg484-1 -directive AlternateRoutability -keep_equivalent_registers -no_lc -no_srlextract -shreg_min_size 10


write_checkpoint -force -noxdef huffman_decoder.dcp

catch { report_utilization -file huffman_decoder_utilization_synth.rpt -pb huffman_decoder_utilization_synth.pb }
